import { Inter, Roboto, Poppins} from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer/Footer";
import Navbar from "@/components/navbar/Navbar";

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Full-stack Next js App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">        
          <Navbar/>
          {children}
          <Footer/>
        </div>
      </body>
    </html>
  );
}
